-- Database Teaching Team
-- Student Starting schema Assignment 2 2020 S2
-- This script must not be altered in ANY WAY

-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538

DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE artwork CASCADE CONSTRAINTS;

DROP TABLE aw_status CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE aw_display CASCADE CONSTRAINTS;

DROP TABLE gallery CASCADE CONSTRAINTS;

DROP TABLE sale CASCADE CONSTRAINTS;

CREATE TABLE artist (
    artist_code     NUMBER(4) NOT NULL,
    artist_gname    VARCHAR2(50),
    artist_fname    VARCHAR2(50),
    artist_street   VARCHAR2(50) NOT NULL,
    artist_town     VARCHAR2(50) NOT NULL,
    artist_state    CHAR(3) NOT NULL,
    artist_phone    CHAR(10),
    artist_noworks  NUMBER(3) NOT NULL
);

COMMENT ON COLUMN artist.artist_code IS
    'Code/Identifier for artist';

COMMENT ON COLUMN artist.artist_gname IS
    'Artist''s given name';

COMMENT ON COLUMN artist.artist_fname IS
    'Artist''s family name';

COMMENT ON COLUMN artist.artist_street IS
    'Street address of artist';

COMMENT ON COLUMN artist.artist_town IS
    'Town address of artist';

COMMENT ON COLUMN artist.artist_state IS
    'State address of artist';

COMMENT ON COLUMN artist.artist_phone IS
    'Phone number of artist';

COMMENT ON COLUMN artist.artist_noworks IS
    'Number of works currently held in stock by MAU for the artist';

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_code );

CREATE TABLE artwork (
    artist_code         NUMBER(4) NOT NULL,
    artwork_no          NUMBER NOT NULL,
    artwork_title       VARCHAR2(100) NOT NULL,
    artwork_minpayment  NUMBER(9, 2) NOT NULL,
    artwork_submitdate  DATE NOT NULL
);

COMMENT ON COLUMN artwork.artist_code IS
    'Code/Identifier for artist';

COMMENT ON COLUMN artwork.artwork_no IS
    'Identifier for artwork within this artist';

COMMENT ON COLUMN artwork.artwork_title IS
    'Title of artwork, note a particular artist must use a unique title for each of their artworks';

COMMENT ON COLUMN artwork.artwork_minpayment IS
    'Minimum payment artist is prepared to accept for the artwork';

COMMENT ON COLUMN artwork.artwork_submitdate IS
    'The date when an artwork is submitted';

ALTER TABLE artwork ADD CONSTRAINT artwork_pk PRIMARY KEY ( artwork_no,
                                                            artist_code );

ALTER TABLE artwork ADD CONSTRAINT artwork_title_uk UNIQUE ( artist_code,
                                                             artwork_title );

CREATE TABLE aw_display (
    aw_display_id          NUMBER(7) NOT NULL,
    artist_code            NUMBER(4) NOT NULL,
    artwork_no             NUMBER NOT NULL,
    aw_display_start_date  DATE NOT NULL,
    aw_display_end_date    DATE,
    gallery_id             NUMBER(3) NOT NULL
);

COMMENT ON COLUMN aw_display.aw_display_id IS
    'surrogate key added to replace display composite PK';

COMMENT ON COLUMN aw_display.artist_code IS
    'Code/Identifier for artist';

COMMENT ON COLUMN aw_display.artwork_no IS
    'Identifier for artwork within this artist';

COMMENT ON COLUMN aw_display.aw_display_start_date IS
    'Date this artwork display in the gallery began';

COMMENT ON COLUMN aw_display.aw_display_end_date IS
    'Date display of this artwork ends';

COMMENT ON COLUMN aw_display.gallery_id IS
    'Identifier for Gallery';

ALTER TABLE aw_display ADD CONSTRAINT aw_display_pk PRIMARY KEY ( aw_display_id );

ALTER TABLE aw_display
    ADD CONSTRAINT aw_display_uq UNIQUE ( aw_display_start_date,
                                          artist_code,
                                          artwork_no );

CREATE TABLE aw_status (
    aws_id         NUMBER(7) NOT NULL,
    artist_code    NUMBER(4) NOT NULL,
    artwork_no     NUMBER NOT NULL,
    aws_date_time  DATE NOT NULL,
    aws_action     CHAR(1) NOT NULL,
    gallery_id     NUMBER(3)
);

ALTER TABLE aw_status
    ADD CONSTRAINT chk_awstatus CHECK ( aws_action IN ( 'G', 'R', 'S', 'T', 'W' ) );

COMMENT ON COLUMN aw_status.aws_id IS
    'surrogate key added to replace aw_status composite PK';

COMMENT ON COLUMN aw_status.artist_code IS
    'Code/Identifier for artist';

COMMENT ON COLUMN aw_status.artwork_no IS
    'Identifier for artwork within this artist';

COMMENT ON COLUMN aw_status.aws_date_time IS
    'Date and time of change status took place';

COMMENT ON COLUMN aw_status.aws_action IS
    'Artwork status
W -  in MAU storage at the MAU central warehouse
T - in transit (being shipped to/from a gallery), include to/from which gallery id
G - located at the gallery, include gallery id
S -  sold, or
R - returned to the artist 

';

COMMENT ON COLUMN aw_status.gallery_id IS
    'Identifier for Gallery';

ALTER TABLE aw_status ADD CONSTRAINT aw_status_pk PRIMARY KEY ( aws_id );

ALTER TABLE aw_status
    ADD CONSTRAINT aw_status_uq UNIQUE ( aws_date_time,
                                         artist_code,
                                         artwork_no );

CREATE TABLE customer (
    customer_id       NUMBER(5) NOT NULL,
    customer_gname    VARCHAR2(50),
    customer_fname    VARCHAR2(50),
    customer_busname  VARCHAR2(100),
    customer_street   VARCHAR2(50) NOT NULL,
    customer_town     VARCHAR2(50) NOT NULL,
    customer_state    CHAR(3) NOT NULL,
    customer_phone    CHAR(10) NOT NULL
);

COMMENT ON COLUMN customer.customer_id IS
    'Identifier for customer within gallery';

COMMENT ON COLUMN customer.customer_gname IS
    'Customers given name';

COMMENT ON COLUMN customer.customer_fname IS
    'Customers family name';

COMMENT ON COLUMN customer.customer_busname IS
    'Business name of customer';

COMMENT ON COLUMN customer.customer_street IS
    'Street address of customer';

COMMENT ON COLUMN customer.customer_town IS
    'Town address of customer';

COMMENT ON COLUMN customer.customer_state IS
    'State address of customer';

COMMENT ON COLUMN customer.customer_phone IS
    'Phone number of customer';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

CREATE TABLE gallery (
    gallery_id            NUMBER(3) NOT NULL,
    gallery_name          VARCHAR2(100) NOT NULL,
    gallery_manager       VARCHAR2(60) NOT NULL,
    gallery_street        VARCHAR2(50) NOT NULL,
    gallery_town          VARCHAR2(50) NOT NULL,
    gallery_state         CHAR(3) NOT NULL,
    gallery_phone         CHAR(10) NOT NULL,
    gallery_sale_percent  NUMBER(4, 1) NOT NULL,
    gallery_open          DATE NOT NULL,
    gallery_close         DATE NOT NULL
);

COMMENT ON COLUMN gallery.gallery_id IS
    'Identifier for Gallery';

COMMENT ON COLUMN gallery.gallery_name IS
    'Name of gallery';

COMMENT ON COLUMN gallery.gallery_manager IS
    'Name of gallery manager';

COMMENT ON COLUMN gallery.gallery_street IS
    'Street address of gallery';

COMMENT ON COLUMN gallery.gallery_town IS
    'Town address of gallery';

COMMENT ON COLUMN gallery.gallery_state IS
    'State address of gallery';

COMMENT ON COLUMN gallery.gallery_phone IS
    'Phone number of gallery';

COMMENT ON COLUMN gallery.gallery_sale_percent IS
    'Percentage of sale for gallery';

COMMENT ON COLUMN gallery.gallery_open IS
    'Open time of gallery';

COMMENT ON COLUMN gallery.gallery_close IS
    'Close time of gallery';

ALTER TABLE gallery ADD CONSTRAINT gallery_pk PRIMARY KEY ( gallery_id );

ALTER TABLE gallery ADD CONSTRAINT gallery_phone_uk UNIQUE ( gallery_phone );

CREATE TABLE sale (
    sale_id        NUMBER(5) NOT NULL,
    sale_date      DATE NOT NULL,
    sale_price     NUMBER(9, 2) NOT NULL,
    customer_id    NUMBER(5) NOT NULL,
    aw_display_id  NUMBER(7) NOT NULL
);

COMMENT ON COLUMN sale.sale_id IS
    'Identifier for sale';

COMMENT ON COLUMN sale.sale_date IS
    'Date sale was closed';

COMMENT ON COLUMN sale.sale_price IS
    'Price customer paid for painting';

COMMENT ON COLUMN sale.customer_id IS
    'Identifier for customer within gallery';

COMMENT ON COLUMN sale.aw_display_id IS
    'surrogate key added to replace display composite PK';

CREATE UNIQUE INDEX sale__idx ON
    sale (
        aw_display_id
    ASC );

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( sale_id );

ALTER TABLE artwork
    ADD CONSTRAINT artist_artwork FOREIGN KEY ( artist_code )
        REFERENCES artist ( artist_code );

ALTER TABLE aw_status
    ADD CONSTRAINT artwork_aw_status FOREIGN KEY ( artwork_no,
                                                   artist_code )
        REFERENCES artwork ( artwork_no,
                             artist_code );

ALTER TABLE aw_display
    ADD CONSTRAINT artwork_gallery FOREIGN KEY ( artwork_no,
                                                 artist_code )
        REFERENCES artwork ( artwork_no,
                             artist_code );

ALTER TABLE sale
    ADD CONSTRAINT customer_sale FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id );

ALTER TABLE aw_status
    ADD CONSTRAINT gallery_aw_status FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );

ALTER TABLE aw_display
    ADD CONSTRAINT gallery_exhibit FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );

ALTER TABLE sale
    ADD CONSTRAINT sale_exhibit FOREIGN KEY ( aw_display_id )
        REFERENCES aw_display ( aw_display_id );


--------------------------------------
--INSERT INTO artist
--------------------------------------
INSERT INTO artist VALUES (1, 'Martainn', 'Jenteau', '328 Forest Pass', 'Melbourne', 'VIC', '0495300384', 0);
INSERT INTO artist VALUES (2, 'Kipp', 'Grellis', '2755 Briar Crest Place', 'South Yarra', 'VIC', '0468858093', 0);
INSERT INTO artist VALUES (3, 'Jessi', 'Allward', '9 Becker Plaza', 'Wallan', 'VIC', '0438843662', 0);
INSERT INTO artist VALUES (4, 'Rosalinda', 'Zavattiero', '1 Del Mar Avenue', 'Malvern East', 'VIC', '', 0);
INSERT INTO artist VALUES (5, 'Neda', 'Mylchreest', '327 Caliangt Street', 'Clayton South', 'VIC', '0409562816', 0);
INSERT INTO artist VALUES (6, 'Elga', 'Yakolev', '6 Hanson Park', 'Lysterfield', 'VIC', '0496667027', 0);
INSERT INTO artist VALUES (7, 'Weston', 'Stearndale', '39512 Kipling Road', 'Leongatha', 'VIC', '0417905216', 0);
INSERT INTO artist VALUES (8, 'Reeba', 'Wildman', '92542 Service Junction', 'Malvern East', 'VIC', '0493427245', 0);
INSERT INTO artist VALUES (9, 'Marlee', 'Champerlen', '64201 Carey Circle', 'Clayton South', 'VIC', '0427832032', 0);
INSERT INTO artist VALUES (10, 'Dorette', '', '87596 Porter Place', 'Lysterfield', 'VIC', '0487345845', 0);
INSERT INTO artist VALUES (11, 'Westley', 'Oakenford', '137 Tennessee Street', 'Attwood', 'VIC', '0418289108', 0);
INSERT INTO artist VALUES (12, 'Kilian', 'Moisey', '05422 Pearson Avenue', 'Melbourne', 'VIC', '0429418600', 0);
INSERT INTO artist VALUES (13, 'Monica', 'Nicklinson', '3974 Arapahoe Drive', 'Camira', 'NSW', '0430300769', 0);
INSERT INTO artist VALUES (14, 'Guendolen', 'Munks', '3824 Main Trail', 'Richmond', 'VIC', '0415621231', 0);
INSERT INTO artist VALUES (15, 'Maggi', 'Aaronsohn', '5 Garrison Terrace', 'Manning', 'WA', '0459159292', 0);
INSERT INTO artist VALUES (16, 'Maggy', 'Jindacek', '41 Daystar Parkway', 'Lysterfield South', 'VIC', '0468567430', 0);
INSERT INTO artist VALUES (17, '', 'Duddy', '31 Golf Terrace', 'Lysterfield', 'VIC', '0424396443', 0);
INSERT INTO artist VALUES (18, 'Harli', 'Bard', '65 Old Shore Alley', 'Lysterfield', 'VIC', '0405184650', 0);
INSERT INTO artist VALUES (19, 'Patten', 'Martyn', '6214 Continental Parkway', 'Richmond East', 'VIC', '0449053430', 0);
INSERT INTO artist VALUES (20, 'Adrianna', 'Dugget', '9 Declaration Parkway', 'Belgrave', 'VIC', '', 0);
INSERT INTO artist VALUES (21, 'Wade', 'Nutley', '1 Petterle Hill', 'Melbourne', 'VIC', '0406262943', 0);


--------------------------------------
--INSERT INTO customer
--------------------------------------
INSERT INTO customer VALUES (1, 'Florida', 'Goldhawk', '', '904 Talmadge Lane', 'Belgrave', 'VIC', '0454762942');
INSERT INTO customer VALUES (2, 'Marina', 'Clements', '', '4632 Monica Plaza', 'Belgrave South', 'VIC', '0425271315');
INSERT INTO customer VALUES (3, 'Stefanie', 'Wilstead', '', '1723 Dottie Parkway', 'Pakenham', 'VIC', '0452272267');
INSERT INTO customer VALUES (4, '', '', 'Quinlan Temperley Pvt. Ltd.', '1 Kinsman Terrace', 'Melbourne', 'VIC', '0475110074');
INSERT INTO customer VALUES (5, 'Lois', 'Hawkshaw', '', '7480 Center Crossing', 'Pakenham Upper', 'VIC', '0458708402');
INSERT INTO customer VALUES (6, 'Reinald', 'Sedwick', '', '2422 Calypso Circle', 'Leongatha', 'VIC', '0489832003');
INSERT INTO customer VALUES (7, 'Jobie', 'Pheazey', '', '03 New Castle Center', 'Leongatha', 'VIC', '0475761206');
INSERT INTO customer VALUES (8, '', '', 'Rochelle Zecchinii Pvt. Ltd.', '10 Forest Dale Terrace', 'Melbourne', 'VIC', '0409646679');
INSERT INTO customer VALUES (9, 'Danila', 'Geraldo', '', '9 Londonderry Parkway', 'Leongatha', 'VIC', '0464179129');
INSERT INTO customer VALUES (10, 'Haleigh', 'Bonifacio', '', '93 Buell Lane', 'Malvern East', 'VIC', '0480445917');


--------------------------------------
--INSERT INTO gallery
--------------------------------------
INSERT INTO gallery VALUES (1, 'Karma Art', 'Seline Fortey', '9 Mallory Court', 'Attwood', 'VIC', '0413432569', 5.6, TO_DATE('9:30', 'HH24:MI'), TO_DATE('17:30', 'HH24:MI'));
INSERT INTO gallery VALUES (2, 'Artology', 'Charmaine Gehrtz', '9 Gerald Park', 'Melbourne', 'VIC', '0474980815', 10.3, TO_DATE('9:00', 'HH24:MI'), TO_DATE('18:00', 'HH24:MI'));
INSERT INTO gallery VALUES (3, 'Inspire Art', 'Malissa McGlynn', '327 Rigney Plaza', 'Camira', 'VIC', '0417407587', 7.5, TO_DATE('10:00', 'HH24:MI'), TO_DATE('18:00', 'HH24:MI'));
INSERT INTO gallery VALUES (4, 'Art Smart', 'Ferrell Byard', '04 Florence Alley', 'Richmond', 'VIC', '0490556646', 9.6, TO_DATE('10:00', 'HH24:MI'), TO_DATE('18:00', 'HH24:MI'));
INSERT INTO gallery VALUES (5, 'Art Temple', 'Bernard Msard', '123 Hyde Park', 'South Yarra', 'VIC', '0438093219', 10.5, TO_DATE('10:00', 'HH24:MI'), TO_DATE('18:00', 'HH24:MI'));

commit;
